[project]
name = "ia2"
version = "0.1.0"
dependencies = [
    "pycairo",
    "pygame-ce",
    "numpy",
    "scipy",
]

[project.optional-dependencies]
opengl = ["moderngl"]

[tool.setuptools]
packages = ["ia2"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
